export default {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  REFRESH_REQUEST: "REFRESH_REQUEST",
  REFRESH_SUCCESS: "REFRESH_SUCCESS",
  REFRESH_ERROR: "REFRESH_ERROR",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  GET_INFO_FROM_FORM: "GET_INFO_FROM_FORM",
  CALC_SUMMARY: "CALC_SUMMARY"
};
